# Generated by Django 4.2.20 on 2025-11-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_alter_availability_options_serviceavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='use_custom_availability',
            field=models.BooleanField(default=False, help_text="If False, uses provider's default availability. If True, uses custom schedule below."),
        ),
    ]
