# Generated by Django 4.2.20 on 2025-11-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_service_use_custom_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceavailability',
            options={'ordering': ['day_of_week', 'start_time'], 'verbose_name': 'Service Availability', 'verbose_name_plural': 'Service Availabilities'},
        ),
        migrations.AlterField(
            model_name='serviceavailability',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='serviceavailability',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='serviceavailability',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='serviceavailability',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_availability', to='providers.service'),
        ),
        migrations.AlterField(
            model_name='serviceavailability',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
