# Generated by Django 4.2.20 on 2025-11-30 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_alter_serviceavailability_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['service_provider', 'service_id', 'day_of_week', 'display_order'], 'verbose_name': 'Availability', 'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='availability',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Ordering for multiple slots on same day'),
        ),
        migrations.AddField(
            model_name='availability',
            name='service',
            field=models.ForeignKey(blank=True, help_text='If empty, this row is a provider default and applies to all services that do not have custom hours.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_availability', to='providers.service'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='providers.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='use_custom_availability',
            field=models.BooleanField(default=False, help_text="If False, uses provider's default availability. If True, uses custom schedule set for this service."),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('service_provider', 'service', 'day_of_week', 'display_order')},
        ),
        migrations.DeleteModel(
            name='ServiceAvailability',
        ),
    ]
