# Generated by Django 4.2.20 on 2025-11-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_alter_availability_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='use_custom_availability',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
