# Generated by Django 4.2.20 on 2025-11-30 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_remove_service_use_custom_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='use_custom_availability',
            field=models.BooleanField(default=False, help_text='If True, this service will use its own custom availability instead of provider defaults'),
        ),
        migrations.CreateModel(
            name='ServiceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_availability', to='providers.service')),
            ],
            options={
                'verbose_name': 'Service Availability',
                'verbose_name_plural': 'Service Availabilities',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceavailability',
            constraint=models.UniqueConstraint(fields=('service', 'day_of_week'), name='unique_service_day'),
        ),
    ]
