# Generated by Django 4.2.20 on 2025-11-30 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_service_use_custom_availability_serviceavailability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='about_us',
            field=models.TextField(blank=True, help_text='Tell clients about your business, history, values', null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='cancellation_policy_url',
            field=models.URLField(blank=True, help_text='Link to your Cancellation Policy (can be external)', null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload your business logo (recommended: 500x500px square)', null=True, upload_to='provider_logos/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='mission_statement',
            field=models.TextField(blank=True, help_text='What is your business mission?', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='privacy_policy_url',
            field=models.URLField(blank=True, help_text='Link to your Privacy Policy (can be external)', null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='terms_conditions_url',
            field=models.URLField(blank=True, help_text='Link to your Terms & Conditions (can be external like Notion, Google Docs)', null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='vision_statement',
            field=models.TextField(blank=True, help_text='What is your long-term vision?', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonial_photos/')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('testimonial_text', models.TextField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='providers.serviceprovider')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/')),
                ('role_title', models.CharField(help_text='e.g., Senior Stylist, Yoga Instructor', max_length=200)),
                ('specialties', models.TextField(blank=True, help_text='e.g., Hair coloring, Keratin treatments', null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('credentials', models.TextField(blank=True, help_text='e.g., MBA, 10 years experience', null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='providers.serviceprovider')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_images', to='providers.serviceprovider')),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
