# Generated by Django 4.2.20 on 2025-11-30 11:50

from django.db import migrations, models
import providers.models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_serviceprovider_about_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(upload_to=providers.models.upload_hero_image),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload your business logo (recommended: 500x500px square)', null=True, upload_to=providers.models.upload_logo),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Business logo or profile picture', null=True, upload_to=providers.models.upload_profile_image),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=providers.models.upload_team_photo),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_photo',
            field=models.ImageField(blank=True, null=True, upload_to=providers.models.upload_testimonial_photo),
        ),
    ]
