# Generated by Django 4.2.20 on 2025-12-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0012_alter_heroimage_image_alter_serviceprovider_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='hero_color',
            field=models.CharField(blank=True, default='#7c3aed', help_text='Hero section background color (hex code, e.g., #7c3aed)', max_length=7, null=True),
        ),
    ]
