# Generated by Django 4.2.20 on 2025-12-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0013_serviceprovider_hero_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='hero_color',
            field=models.CharField(blank=True, default='#7c3aed', help_text='Hero section background color (hex format, e.g., #7c3aed)', max_length=7, null=True),
        ),
    ]
