# Generated by Django 4.2.20 on 2025-12-01 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0014_add_hero_color'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('sms_enabled', models.BooleanField(default=True, help_text='Receive SMS notifications (if provider has PRO plan)')),
                ('booking_confirmation', models.BooleanField(default=True, help_text='Receive booking confirmation notifications')),
                ('appointment_reminders', models.BooleanField(default=True, help_text='Receive appointment reminder notifications')),
                ('cancellation_updates', models.BooleanField(default=True, help_text='Receive cancellation/rescheduling notifications')),
                ('promotional_emails', models.BooleanField(default=False, help_text='Receive promotional emails from providers')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='FavoriteProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_providers', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='providers.serviceprovider')),
            ],
            options={
                'verbose_name': 'Favorite Provider',
                'verbose_name_plural': 'Favorite Providers',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'provider')},
            },
        ),
    ]
